### PR TITLE
create separate folders for each module

### PR DESCRIPTION
**Pull request by varunpatro**

### CODE REVIEW

**Comment by yangshun** [comment]
This is unexpected behaviour and will not provide a good user experience. Personally I selected the directory I want to save to and I don't expect any further directories to be created. Also, users have the option to create a new folder when they select the folder path. So they can already create the folder for the module. IMO this is unnecessary.

**Comment by xinan** [comment]
Could you make it a
- [x] checkbox 

option? Some people may like it, some may not like it. An checkbox option below the destination field will be good.

**Comment by Ohohcakester** [comment]
It would probably make sense as an option (checkbox) if we allow "batch" downloading for multiple modules at once. e.g. "MA3110, MA3252, CS3230"
Otherwise I agree with yangshun on this.

**Comment by varunpatro** [comment]
I download all my papers at once, so for me, it'll be good to have separate module folders.

@Ohohcakester - you're idea seems ideal. let me work on it.

**Pull request closed without merging**
